=== cugni/aeneas/aeneas-1/CassandraBM/model/src/main/resources/CassandraModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://cassamdrabm.bsc.es/CassandraModel" 
        xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" elementFormDefault="qualified"
        xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes">
    <import namespace="http://cassamdrabm.bsc.es/CommonTypes" schemaLocation="CommonTypes.xsd"/>
    <complexType name="KeyspaceType">
        <sequence>
            <element name="strategy" type="tns:StrategyType"></element>
            <element name="replicationFactor" type="int"></element>
            <element name="columnFamily" type="tns:ColumnFamilyType"
                     maxOccurs="unbounded">
            </element>
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>
    <element name="keyspace" type="tns:KeyspaceType"></element>
    <complexType name="ColumnFamilyType">
        <sequence>       
            <element name="consistency" minOccurs="0" type="tns:ConsistencyType"/>
            <element name="keyCacheSize" minOccurs="0" type="double"/>
            <element name="keyCachePeriod" minOccurs="0" type="int">
                <annotation>
                    <documentation>Row cache save period in seconds</documentation>
                </annotation>
            </element>
            <element name="rowCacheSize" minOccurs="0" type="double"/>
            <element name="rowCachePeriod" minOccurs="0" type="int">
                <annotation>
                    <documentation>Row cache save period in seconds</documentation>
                </annotation>
            </element>
<!--           <element name="columnSorter" type="tns:ColumnSorterType"></element>
            <element name="key"  type="cmt:SuperType">
                
            </element>-->
            <element name="fixedRow" type="tns:FixedRowType"
                     minOccurs="0" maxOccurs="unbounded">
            </element>
            <element name="column" type="tns:ColumnType"
                     maxOccurs="unbounded" minOccurs="0">
            </element>
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>
    <complexType name="FixedColumnName">
        <complexContent>
            <extension base="cmt:namedType">
                <attribute name="position" type="int" default="0" />
            </extension>
        </complexContent>
        
    </complexType>
    <complexType name="ColumnType">
        <sequence>
            <element name="fixedColumnName" type="tns:FixedColumnName" minOccurs="0">
                <annotation>
                    <documentation>The value of the name would be parsed using the type and used as generic column name</documentation>
                </annotation>
            </element>
            <element name="refPath" type="tns:refPathType"></element>
            <element name="valueless" minOccurs="0"></element>           
        </sequence>
       
        <attribute name="name" default="">
            <annotation>
                <documentation>
                    The attribute name is not used by the framework. It is defined only to provide a memonic handler to the developer
                </documentation>
            </annotation>
           
        </attribute>
        <attribute name="index" default="false" type="boolean"></attribute>
    </complexType>
    <simpleType name="ClassNameType">
        <restriction base="string"></restriction>
    </simpleType>


    <complexType name="FixedRowType">
        <sequence>
            <element name="key" type="cmt:fixedType" maxOccurs="unbounded"></element>
            <element name="column" type="tns:ColumnType" maxOccurs="unbounded"></element>
        </sequence>
    </complexType>




    <simpleType name="StrategyType">
        <restriction base="string">
            <enumeration value="SimpleStrategy"></enumeration>
            <enumeration value="NetworkTopologyStrategy"></enumeration>
            <enumeration value="OldNetworkTopologyStrategy"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="refPathType">
    
        <sequence>
            <element name="level" type="tns:levelType" maxOccurs="unbounded"></element>
            <element name="keyDest" type="tns:KeyDest" minOccurs="0" maxOccurs="unbounded" />
            <element name="columnDest" type="tns:ColumnDest" minOccurs="0" maxOccurs="unbounded"/>
            <element name="valueDest" type="tns:ValueDest" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        
    </complexType>
    <complexType name="KeyDest" >
        <complexContent>
            <extension base="tns:Dest"/>
        </complexContent>
    </complexType>
    <complexType name="ColumnDest" >
        <complexContent>
            <extension base="tns:Dest"/>
        </complexContent>
    </complexType>
    <complexType name="ValueDest" >
        <complexContent>
            <extension base="tns:Dest"/>
        </complexContent>
    </complexType>
    
    <complexType name="Dest">
        
        <sequence>
            <element name="clusterer" type="tns:clustererType" minOccurs="0" maxOccurs="1" />
        </sequence>
        <attribute name="position" type="int" use="required"></attribute>
        <attribute name="attr" type="string" use="optional" default="" />
    </complexType>
    <complexType name="clustererType">
        <attribute name="from" type="string" use="required" />
        <attribute name="to" type="string" use="required" />
        <attribute name="intervals" type="integer" use="required" />
        <attribute name="className" type="string" use="optional" />
    </complexType>
    <simpleType name="ConsistencyType">
        <restriction base="string">
            <enumeration value="ANY" />
            <enumeration value="ONE" />
            <enumeration value="TWO" />
            <enumeration value="THREE" />
            <enumeration value="LOCAL_QUORUM" />
            <enumeration value="EACH_QUORUM" />
            <enumeration value="QUORUM" />
            <enumeration value="ALL" />

        </restriction>
      
    </simpleType>

    <complexType name="levelType">
        <sequence>
            <element name="keyDest" type="tns:KeyDest" minOccurs="0" maxOccurs="unbounded" />
            <element name="columnDest" type="tns:ColumnDest" minOccurs="0" maxOccurs="unbounded"/>
            <element name="valueDest" type="tns:ValueDest" minOccurs="0" maxOccurs="unbounded"/>
            
        </sequence>
        <attribute name="value" type="string" use="required"></attribute>
    </complexType>
</schema>

=== cugni/aeneas/aeneas-1/CassandraBM/cassandra-metrics-recorder/src/main/resources/metricspace.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
              xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel ../../../../model/src/main/resources/CassandraModel.xsd"
              name="metricspace">            
    <tns:strategy>SimpleStrategy</tns:strategy>    
    <tns:replicationFactor>1</tns:replicationFactor>
    <tns:columnFamily name="lists">
        <tns:fixedRow>
             <tns:key  type="UTF8Type">tests-list</tns:key>
             <tns:column name="test-list">     
                <tns:refPath > <!-- This indicates to use the value as column name -->
                    <tns:level value="context"/>
                    <tns:level value="testname"  >
                          <tns:columnDest position="0"/> 
                    </tns:level>
                    <tns:level value="location" />
                    <tns:level value="start"/>  
                </tns:refPath>  
                <tns:valueless/>
            </tns:column>
        </tns:fixedRow>       
        <tns:fixedRow>
             <tns:key  type="UTF8Type">nodes-list</tns:key>
             <tns:column name="nodes-list">     
                <tns:refPath > <!-- This indicates to use the value as column name -->
                    <tns:level value="context" >
                           <tns:columnDest position="0"/> 
                    </tns:level>                   
                    <tns:level value="testname" />
                    <tns:level value="location" >
                          <tns:columnDest position="1"/> 
                    </tns:level>
                    <tns:level value="start"/>  
                </tns:refPath>  
                <tns:valueless/>
            </tns:column>
        </tns:fixedRow> 
         <tns:fixedRow>
             <tns:key  type="UTF8Type">context-list</tns:key>
             <tns:column name="context-list">     
                <tns:refPath > <!-- This indicates to use the value as column name -->
                    <tns:level value="context" >
                           <tns:columnDest position="0"/> 
                    </tns:level>                   
                    <tns:level value="testname" />
                    <tns:level value="location" >
                          <tns:columnDest position="1"/> 
                    </tns:level>
                    <tns:level value="start"/>  
                </tns:refPath>  
                <tns:valueless/>
            </tns:column>
        </tns:fixedRow> 
    </tns:columnFamily>     
    <tns:columnFamily name="tests">       
        
              <tns:column name="start">     
            <tns:fixedColumnName name="start" position="2">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>     
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="context">
                      <tns:keyDest position="0"/>   
                </tns:level>
                <tns:level value="testname" >    
                  <tns:columnDest position="0"/>      
              </tns:level>
              <tns:level value="location" >
               <tns:columnDest position="1"/>      
              </tns:level>                 
                <tns:level value="start"/>  
                <tns:valueDest position="0"/>           
            </tns:refPath>  
        </tns:column>
         <tns:column name="stop">     
            <tns:fixedColumnName name="stop" position="2">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>     
           <tns:refPath > <!-- This indicates to use the value as column name -->
                  <tns:level value="context">
                      <tns:keyDest position="0"/>   
                </tns:level>
                <tns:level value="testname" >    
                  <tns:columnDest  position="0"/>      
              </tns:level>             
              <tns:level value="location" > 
                                 <tns:columnDest position="1"/>      
                </tns:level>                
                <tns:level value="stop"/>  
                <tns:valueDest position="0"/>           
            </tns:refPath>    
        </tns:column>
            
    </tns:columnFamily>
    <tns:columnFamily name="metrics">
        <tns:column name="metricsSingle">           
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="context">
                    <tns:keyDest position="0"/>
                    
                </tns:level>
                <tns:level value="testname">
                    <tns:keyDest position="1"/>
                </tns:level>                
                <tns:level value="location">
                     <tns:keyDest position="2"/>
                </tns:level>     
                <tns:level value="time">
                    <tns:columnDest position="1"/>
                </tns:level>             
                <tns:level value="attribute">
                    <tns:columnDest position="0"/>
                </tns:level> 
                
                <tns:valueDest position="0"/>
            </tns:refPath>             
        </tns:column>
<!--        <tns:column name="metricsGroup">           
            <tns:refPath >  This indicates to use the value as column name 
                <tns:level value="context">
                    <tns:keyDest position="0"/>
                    
                </tns:level>
                <tns:level value="testname">
                    <tns:keyDest position="1"/>
                </tns:level>                
                <tns:level value="location">
                    <tns:keyDest position="2"/>
                </tns:level>     
                <tns:level value="time">
                    <tns:columnDest position="0"/>
                </tns:level>     
                <tns:level value="group">
                    <tns:columnDest position="1"/>
                </tns:level>         
                <tns:level value="attribute">
                    <tns:columnDest position="2"/>
                </tns:level> 
                
                <tns:valueDest position="0"/>
            </tns:refPath>             
        </tns:column>-->
    </tns:columnFamily>
</tns:keyspace>

=== cugni/aeneas/aeneas-2/aeneas-core/loader/target/test-classes/pointsBOP.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
              xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel ../src/main/resources/CassandraModel.xsd"
              name="pointxbop">            
    <tns:strategy>SimpleStrategy</tns:strategy>
    <tns:replicationFactor>1</tns:replicationFactor>

    <tns:columnFamily name="frame">
        <tns:fixedRow>
            <tns:key type="Int32Type">-1</tns:key>
            <tns:column name="number of atoms">          
                <tns:fixedColumnName name="natoms">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
               
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                    <tns:level value="natoms"/>
                </tns:refPath>
            </tns:column>
            <tns:column name="precision">
         
                <tns:fixedColumnName name="prec">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
                
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                    <tns:level value="prec"/>
                </tns:refPath> 		
            </tns:column>
        </tns:fixedRow>
        <tns:column name="step">
         
            <tns:fixedColumnName name="step">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
             
            <tns:refPath>
                <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                <tns:level value="step"/>
            </tns:refPath>
        </tns:column>
        <tns:column name="box">
            <tns:fixedColumnName name="box">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath>
                <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                <tns:level value="box"/>
            </tns:refPath>
        </tns:column>       
    </tns:columnFamily>
    <tns:columnFamily name="points">
        <tns:column index="true" name="point frame">
            <tns:fixedColumnName name="frame">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath> <!-- This indicates to use the value as column name -->
                <tns:level value="frame">
                    <tns:valueDest position="0"/>
                </tns:level> 
                <tns:level value="points"/>
                <tns:level value="index" />
                <tns:keyDest position="0"/>
            </tns:refPath>
        </tns:column>
        <tns:column index="true" name="point id">
            <tns:fixedColumnName name="point">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="frame" />
                <tns:level value="points"/>
                <tns:level value="index">
                    <tns:valueDest position="0"/>
                </tns:level> 
                <tns:keyDest position="0"/>
            </tns:refPath>
        </tns:column>
    </tns:columnFamily>
    <tns:columnFamily name="time">
        <tns:column name="time">
            <tns:refPath>
                <tns:level value="frame">
                    <tns:columnDest position="0"/>
                </tns:level> 
                <tns:level value="time" />
                <tns:keyDest position="0"/>
            </tns:refPath>  
            <tns:valueless></tns:valueless>
        </tns:column>
    </tns:columnFamily>
</tns:keyspace>
