=== cugni/aeneas/aeneas-1/CassandraBM/model/src/main/resources/CassandraModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://cassamdrabm.bsc.es/CassandraModel" 
        xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" elementFormDefault="qualified"
        xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes">
    <import namespace="http://cassamdrabm.bsc.es/CommonTypes" schemaLocation="CommonTypes.xsd"/>
    <complexType name="KeyspaceType">
        <sequence>
            <element name="strategy" type="tns:StrategyType"></element>
            <element name="replicationFactor" type="int"></element>
            <element name="columnFamily" type="tns:ColumnFamilyType"
                     maxOccurs="unbounded">
            </element>
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>
    <element name="keyspace" type="tns:KeyspaceType"></element>
    <complexType name="ColumnFamilyType">
        <sequence>       
            <element name="consistency" minOccurs="0" type="tns:ConsistencyType"/>
            <element name="keyCacheSize" minOccurs="0" type="double"/>
            <element name="keyCachePeriod" minOccurs="0" type="int">
                <annotation>
                    <documentation>Row cache save period in seconds</documentation>
                </annotation>
            </element>
            <element name="rowCacheSize" minOccurs="0" type="double"/>
            <element name="rowCachePeriod" minOccurs="0" type="int">
                <annotation>
                    <documentation>Row cache save period in seconds</documentation>
                </annotation>
            </element>
<!--           <element name="columnSorter" type="tns:ColumnSorterType"></element>
            <element name="key"  type="cmt:SuperType">
                
            </element>-->
            <element name="fixedRow" type="tns:FixedRowType"
                     minOccurs="0" maxOccurs="unbounded">
            </element>
            <element name="column" type="tns:ColumnType"
                     maxOccurs="unbounded" minOccurs="0">
            </element>
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>
    <complexType name="FixedColumnName">
        <complexContent>
            <extension base="cmt:namedType">
                <attribute name="position" type="int" default="0" />
            </extension>
        </complexContent>
        
    </complexType>
    <complexType name="ColumnType">
        <sequence>
            <element name="fixedColumnName" type="tns:FixedColumnName" minOccurs="0">
                <annotation>
                    <documentation>The value of the name would be parsed using the type and used as generic column name</documentation>
                </annotation>
            </element>
            <element name="refPath" type="tns:refPathType"></element>
            <element name="valueless" minOccurs="0"></element>           
        </sequence>
       
        <attribute name="name" default="">
            <annotation>
                <documentation>
                    The attribute name is not used by the framework. It is defined only to provide a memonic handler to the developer
                </documentation>
            </annotation>
           
        </attribute>
        <attribute name="index" default="false" type="boolean"></attribute>
    </complexType>
    <simpleType name="ClassNameType">
        <restriction base="string"></restriction>
    </simpleType>


    <complexType name="FixedRowType">
        <sequence>
            <element name="key" type="cmt:fixedType" maxOccurs="unbounded"></element>
            <element name="column" type="tns:ColumnType" maxOccurs="unbounded"></element>
        </sequence>
    </complexType>




    <simpleType name="StrategyType">
        <restriction base="string">
            <enumeration value="SimpleStrategy"></enumeration>
            <enumeration value="NetworkTopologyStrategy"></enumeration>
            <enumeration value="OldNetworkTopologyStrategy"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="refPathType">
    
        <sequence>
            <element name="level" type="tns:levelType" maxOccurs="unbounded"></element>
            <element name="keyDest" type="tns:KeyDest" minOccurs="0" maxOccurs="unbounded" />
            <element name="columnDest" type="tns:ColumnDest" minOccurs="0" maxOccurs="unbounded"/>
            <element name="valueDest" type="tns:ValueDest" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        
    </complexType>
    <complexType name="KeyDest" >
        <complexContent>
            <extension base="tns:Dest"/>
        </complexContent>
    </complexType>
    <complexType name="ColumnDest" >
        <complexContent>
            <extension base="tns:Dest"/>
        </complexContent>
    </complexType>
    <complexType name="ValueDest" >
        <complexContent>
            <extension base="tns:Dest"/>
        </complexContent>
    </complexType>
    
    <complexType name="Dest">
        
        <sequence>
            <element name="clusterer" type="tns:clustererType" minOccurs="0" maxOccurs="1" />
        </sequence>
        <attribute name="position" type="int" use="required"></attribute>
        <attribute name="attr" type="string" use="optional" default="" />
    </complexType>
    <complexType name="clustererType">
        <attribute name="from" type="string" use="required" />
        <attribute name="to" type="string" use="required" />
        <attribute name="intervals" type="integer" use="required" />
        <attribute name="className" type="string" use="optional" />
    </complexType>
    <simpleType name="ConsistencyType">
        <restriction base="string">
            <enumeration value="ANY" />
            <enumeration value="ONE" />
            <enumeration value="TWO" />
            <enumeration value="THREE" />
            <enumeration value="LOCAL_QUORUM" />
            <enumeration value="EACH_QUORUM" />
            <enumeration value="QUORUM" />
            <enumeration value="ALL" />

        </restriction>
      
    </simpleType>

    <complexType name="levelType">
        <sequence>
            <element name="keyDest" type="tns:KeyDest" minOccurs="0" maxOccurs="unbounded" />
            <element name="columnDest" type="tns:ColumnDest" minOccurs="0" maxOccurs="unbounded"/>
            <element name="valueDest" type="tns:ValueDest" minOccurs="0" maxOccurs="unbounded"/>
            
        </sequence>
        <attribute name="value" type="string" use="required"></attribute>
    </complexType>
</schema>

=== cugni/aeneas/aeneas-1/CassandraBM/loader/src/test/resources/columnCompositePxF.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
              xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel ../src/main/resources/CassandraModel.xsd"
              name="columncompositepxf">            
    <tns:strategy>SimpleStrategy</tns:strategy>
    <tns:replicationFactor>1</tns:replicationFactor>

    <tns:columnFamily name="framemetadata">
        <tns:fixedRow>
            <tns:key type="Int32Type">-1</tns:key>
            <tns:column name="number of atoms">
          
                <tns:fixedColumnName name="natoms">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
               
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                    <tns:level value="natoms"/>
                </tns:refPath>
            </tns:column>
            <tns:column name="precision">
         
                <tns:fixedColumnName name="prec">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
                
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                    <tns:level value="prec"/>
                </tns:refPath> 		
            </tns:column>
        </tns:fixedRow>
        <tns:column name="step">
         
            <tns:fixedColumnName name="step">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
             
            <tns:refPath>
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="step"/>
            </tns:refPath>
        </tns:column>
        <tns:column name="box">
            <tns:fixedColumnName name="box">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath>
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="box"/>
            </tns:refPath>
        </tns:column>       
    </tns:columnFamily>
    <tns:columnFamily name="pointsrev">
        <tns:column name="composite points">
            <tns:refPath  > 
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="points"/>
                <tns:level value="index">
                    <tns:columnDest position="1"/>
                </tns:level> 
                <tns:columnDest position="0"/><!-- This indicates to use the value as column name -->
            </tns:refPath>
            <tns:valueless></tns:valueless>
        </tns:column>
        
    </tns:columnFamily>
    <tns:columnFamily name="pointspfv">
        <tns:column name="k=p,cn=f,cv=point value">
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="frame">
                    <tns:columnDest position="0"/>
                </tns:level>
                <tns:level value="points"/>
                <tns:level value="index" >
                    <tns:keyDest position="0"/>
                </tns:level>
            </tns:refPath>
        </tns:column>
        
    </tns:columnFamily>
    
    <tns:columnFamily name="time">
        <tns:fixedRow>
            <tns:key type="Int32Type">-1</tns:key>
            <tns:column name="time">                   
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:columnDest position="1"/>
                    </tns:level> 
                    <tns:level value="time" />
                    <tns:columnDest position="0"/>
                </tns:refPath>  
                <tns:valueless></tns:valueless>
            </tns:column>
        </tns:fixedRow>
    </tns:columnFamily>
</tns:keyspace>

=== cugni/aeneas/node-agent/src/main/resources/workspace.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
              xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel ../../../../model/src/main/resources/CassandraModel.xsd"
              name="workspace">            
    <tns:strategy>SimpleStrategy</tns:strategy>    
    <tns:replicationFactor>1</tns:replicationFactor>
    
   
    <tns:columnFamily name="workspace">     
        <tns:column id="desc">
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="workspace" >
                    <tns:keyDest position=""/>
                </tns:level>
                <tns:level value="desc"  >
                    <tns:columnDest position="0"/> 
                </tns:level>
            </tns:refPath>              
        </tns:column>
        <tns:column id="creationTime">
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="workspace" >
                    <tns:keyDest position=""/>
                </tns:level>
                <tns:level value="creationTime"  >
                    <tns:columnDest position="0"/> 
                </tns:level>
            </tns:refPath>              
        </tns:column>
        <tns:column id="modificationTime">
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="workspace" >
                    <tns:keyDest position=""/>
                </tns:level>
                <tns:level value="modificationTime"  >
                    <tns:columnDest position="0"/> 
                </tns:level>
            </tns:refPath>              
        </tns:column>
    </tns:columnFamily>
    <tns:columnFamily name="sets">
        <tns:column id="sets">
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="workspace" >
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="sets"/>                    
                <tns:level value="sname"  >
                    <tns:columnDest position="0"/> 
                </tns:level>
            </tns:refPath> 
        </tns:column>        
    </tns:columnFamily>
    <tns:columnFamily name="snippets">
        <tns:column id="data">
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="workspace" >
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="sname">
                    <tns:keyDest position="1"/>
                </tns:level>                    
                <tns:level value="data" >                    
                </tns:level>
                <tns:level value="time" >
                    <tns:columnDest position="0"/> 
                </tns:level>        
            </tns:refPath> 
        </tns:column>        
          
    </tns:columnFamily>
    <tns:columnFamily name="tags">
        <tns:column id="tags">
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="workspace" >
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="snippets" />              
                <tns:level value="sname">
                    <tns:keyDest position="1"/>
                </tns:level>                    
                <tns:level value="tag" > 
                    <tns:keyDest position="0">                   
                </tns:level>
  
            </tns:refPath> 
        </tns:column>        
    </tns:columnFamily>
</tns:keyspace>

=== cugni/aeneas/aeneas-1/bscproj1/bsc01-loader-impl/src/main/resources/conf/DOP2LevelPerfect.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
              xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel ../src/main/resources/CassandraModel.xsd"
              name="DOP2LevelPerfect">            
    <tns:strategy>SimpleStrategy</tns:strategy>
    <tns:replicationFactor>1</tns:replicationFactor>

    <tns:columnFamily name="framemeta">
        <tns:keyCacheSize>200.0</tns:keyCacheSize>
        <tns:keyCachePeriod>60</tns:keyCachePeriod>
        <tns:rowCacheSize>100</tns:rowCacheSize>
        <tns:rowCachePeriod>120</tns:rowCachePeriod>
        <tns:fixedRow>
            <tns:key type="Int32Type">-1</tns:key>
            <tns:column>
          
                <tns:fixedColumnName name="natoms">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
               
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                    <tns:level value="natoms"/>
                    
                </tns:refPath>
            </tns:column>
            <tns:column>
         
                <tns:fixedColumnName name="prec">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
                
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:keyDest position="0"/>
                    </tns:level>
                    <tns:level value="prec"/>
                </tns:refPath> 		
            </tns:column>
        </tns:fixedRow>
        <tns:column>
            <tns:fixedColumnName name="step">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath>
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="step"/>
            </tns:refPath>
        </tns:column>
        <tns:column>
            <tns:fixedColumnName name="box">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath>
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="box"/>
            </tns:refPath>
        </tns:column>       
    </tns:columnFamily>
    <tns:columnFamily name="time">
        <tns:keyCacheSize>200.0</tns:keyCacheSize>
        <tns:keyCachePeriod>60</tns:keyCachePeriod>
        <tns:rowCacheSize>100</tns:rowCacheSize>
        <tns:rowCachePeriod>120</tns:rowCachePeriod>
        <tns:fixedRow>
            <tns:key type="Int32Type">-2</tns:key>
            <tns:column>
                <tns:refPath>
                    <tns:level value="frame">
                        <tns:valueDest position="0"/>
                    </tns:level>
                    <tns:level value="time" />
                    <tns:columnDest position="0"/>
                </tns:refPath>                  
            </tns:column>
        </tns:fixedRow>
        
    </tns:columnFamily>
    <tns:columnFamily name="pointsindex">
        <tns:column>
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="frame">
                    <tns:columnDest position="1"/>
                </tns:level>
                <tns:level value="points"/>
                <tns:level value="index">
                    <tns:columnDest position="2"/>
                </tns:level>  
                <tns:keyDest position="0" attr="getX"/>
                <tns:columnDest position="0" attr="getY"/>
            </tns:refPath>
            <tns:valueless></tns:valueless>
        </tns:column>
        
    </tns:columnFamily>
    <tns:columnFamily name="points">
        <tns:column>
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="points"/>
                <tns:level value="index">
                    <tns:keyDest position="1"/>
                </tns:level>  
                <tns:columnDest position="0" attr="getZ"/>
                <tns:valueDest position="0"/>
            </tns:refPath>
          
        </tns:column>
        
    </tns:columnFamily>
</tns:keyspace>

=== cugni/aeneas/aeneas-1/bscproj1/bsc01-loader-impl/t1FxP.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
	      xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel CassandraModel.xsd"
              name="RP2NormLevelPerfect">            
    <tns:strategy>SimpleStrategy</tns:strategy>
    <tns:replicationFactor>2</tns:replicationFactor>

      <tns:columnFamily name="points">
           <tns:column name="points">
           
            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="frame">
                   <tns:columnDest position="0"/>
                </tns:level>
                <tns:level value="points"/>                
                <tns:level value="index">
                     <tns:keyDest position="0"/>
                </tns:level>                 
         
            </tns:refPath>             
        </tns:column>
    </tns:columnFamily>
</tns:keyspace>

=== cugni/aeneas/aeneas-1/bscproj1/bsc01-loader-impl/conf/AFsemiclustered32.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
              xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel CassandraModel.xsd"
              name="AFsemiclustered32">
    <tns:strategy>SimpleStrategy</tns:strategy>
    <tns:replicationFactor>1</tns:replicationFactor>

    <tns:columnFamily name="points">
        <tns:column name="points">

            <tns:refPath > <!-- This indicates to use the value as column name -->
                <tns:level value="frame">
                    <tns:keyDest position="0">
<!--                             <tns:clusterer from="0" to="999" intervals="8" />-->
                    </tns:keyDest>
                </tns:level>
                <tns:level value="points"/>
                <tns:level value="index">
                    <tns:keyDest position="1">
                          <tns:clusterer from="0" to="31" intervals="1" />
                    </tns:keyDest>
		     <tns:columnDest position="0"/> 
                </tns:level>

            </tns:refPath>
        </tns:column>
    </tns:columnFamily>
</tns:keyspace>

=== cugni/aeneas/aeneas-2/aeneas-core/model/src/test/resources/test2.cm.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:keyspace xmlns:tns="http://cassamdrabm.bsc.es/CassandraModel" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
              xsi:schemaLocation="http://cassamdrabm.bsc.es/CassandraModel ../../../../model/src/main/resources/CassandraModel.xsd"
              name="testspace">            
    <tns:strategy>SimpleStrategy</tns:strategy>
    <tns:replicationFactor>1</tns:replicationFactor>

    <tns:columnFamily name="frame">
        <tns:keyCacheSize>200.0</tns:keyCacheSize>
        <tns:keyCachePeriod>60</tns:keyCachePeriod>
        <tns:rowCacheSize>100</tns:rowCacheSize>
        <tns:rowCachePeriod>120</tns:rowCachePeriod>
        <tns:fixedRow>
            <tns:key type="Int32Type">-1</tns:key>
            <tns:column name="natoms">
                <tns:fixedColumnName name="natoms">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
                <tns:refPath>
                    <tns:level value="frame"/>
                    <tns:level value="natoms"/>
                    
                </tns:refPath>
            </tns:column>
            <tns:column  index="true" name="prec">
                <tns:fixedColumnName name="prec">
                    <cmt:standardType>UTF8Type</cmt:standardType>
                </tns:fixedColumnName>
                <tns:refPath>
                    <tns:level value="frame"/>
                    <tns:level value="prec"/>
                </tns:refPath> 		
            </tns:column>
        </tns:fixedRow>
         <tns:column name="FxA" >
            <tns:refPath>
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level> 
                <tns:level value="points"/>
                <tns:level value="index">
                    <tns:columnDest position="0"/>
                </tns:level>  
            </tns:refPath>
        </tns:column>
        <tns:column name="step">
            <tns:fixedColumnName name="step">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath>
                <tns:level value="frame">
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="step"/>
            </tns:refPath>
        </tns:column>
        <tns:column name="box">
            <tns:fixedColumnName name="box">
                <cmt:standardType>UTF8Type</cmt:standardType>
            </tns:fixedColumnName>
            <tns:refPath>
                <tns:level value="frame" >
                    <tns:keyDest position="0"/>
                </tns:level>
                <tns:level value="box"/>
            </tns:refPath>
        </tns:column>
    </tns:columnFamily>
    <tns:columnFamily name="time">
        <tns:keyCacheSize>50.0</tns:keyCacheSize>
        <tns:keyCachePeriod>30</tns:keyCachePeriod>
        <tns:rowCacheSize>0.75</tns:rowCacheSize>
        <tns:rowCachePeriod>45</tns:rowCachePeriod>
        <tns:column name="time">
            <tns:refPath >
                <tns:level value="frame">
                    <tns:columnDest position="0"/>
                </tns:level> 
                <tns:level value="time" />
                <tns:keyDest position="0"/>
            </tns:refPath>  
            <tns:valueless></tns:valueless>
        </tns:column>
    </tns:columnFamily>
</tns:keyspace>
