=== cugni/aeneas/aeneas-core/model/src/main/resources/MatchingModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://aeneas.bsc.es/MatchingModel" 
        xmlns:tns="http://aeneas.bsc.es/MatchingModel" elementFormDefault="qualified"
        xmlns:cmt="http://aeneas.bsc.es/CommonTypes">
    <import namespace="http://aeneas.bsc.es/CommonTypes" schemaLocation="CommonTypes.xsd"/>
    
    <element name="env" type="tns:EnvType">   </element> 
        
    <complexType name="EnvType">
        <sequence>
            <element name="cluster" type="tns:ClusterType" minOccurs="1" maxOccurs="unbounded"></element>
        </sequence>
    </complexType>
    
    <complexType name="ClusterType"  abstract="true">
        <sequence >
            <element name="settings" type="tns:SettingsType" minOccurs="0" >
               
            </element>  
            <element name="matches">
                <complexType>
                    <sequence>
                        <element name="match" type="tns:MatchType"
                                 maxOccurs="unbounded" minOccurs="0">
                        </element>
                    </sequence>
                </complexType>
            </element>  
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
        <attribute name="address" type="string" use="required"></attribute>
    </complexType>
    

      
    <complexType name="SettingsType" abstract="true">
        <sequence></sequence>   
    </complexType>
    <complexType name="MatchType">
        <sequence>
            <element name="fixedDests" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="fixedDest" type="tns:FixedDest"  minOccurs="1" maxOccurs="unbounded"  >
                            
                        </element>
                    </sequence>
                </complexType>
                
            </element>
                        
            <element name="refPath" type="tns:refPathType"></element>               
        </sequence>       
        <attribute name="name" default="" use="optional"/>
        <attribute name="crudType" use="required" type="tns:CrudType"/>
    </complexType>
    <simpleType name="CrudType">
        <restriction base="string"> 
            <enumeration value="CREATE"/>
            <enumeration value="READ"/>
            <enumeration value="UPDATE"/>
            <enumeration value="DELETE"/>
            <enumeration value="CREATE_OR_UPDATE"/>
            <enumeration value="READ_OR_DELETE"/>
        </restriction>
    </simpleType>
    <complexType name="refPathType">    
        <sequence>
            <element name="level" type="tns:levelType" maxOccurs="unbounded"></element>            
        </sequence>        
    </complexType>
    <complexType name="levelType">
        <sequence>
            <element name="dest" type="tns:DestType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>
    <complexType name="DestType" abstract="true">
        <sequence>
            <element name="transform" type="tns:TransformType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="attr" type="string" use="optional" default="" />
        <attribute name="where" type="string" use="required"  />
    </complexType> 
    
    <complexType name="FixedDest">
        <sequence>
            <element name="dest" type="tns:DestType"  minOccurs="1" maxOccurs="unbounded"  />
        </sequence>         
        <attribute name="fixedValue" use="required" type="string"></attribute>
        <attribute name="fixedValueType" default="UTF8Type" type="cmt:standardType"></attribute>
    </complexType> 
    <complexType name="TransformType">
        <attribute name="className" type="string"  use="required" />
        <attribute name="methodName" type="string" use="required"  />        
    </complexType>
    <complexType name="ClustererType">
        <complexContent>
            <extension base="tns:clType">
                <attribute name="from" type="string" use="required" />
                <attribute name="to" type="string" use="required" />
                <attribute name="intervals" type="integer" use="required" />        
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="clType">
        <complexContent>
            <restriction base="tns:TransformType">
                <attribute name="methodName" use="required" type="string" fixed="getGroup"  />        
            </restriction>        
        </complexContent>
    </complexType>
     
</schema>

=== cugni/aeneas/aeneas-core/model/src/test/resources/TestXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:env    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://aeneas.bsc.es/MatchingModel'
    xsi:schemaLocation='http://aeneas.bsc.es/MatchingModel file:/home/ccugnasc/workspace/aeneas/aeneas-core/model/src/main/resources/MatchingModel.xsd'>
    <ns1:cluster name="prova" address="127.0.0.1">
        <ns1:settings></ns1:settings>
        <ns1:matches>
            <ns1:match name="CustomersCreate" crudType="CREATE">
                <ns1:refPath>
                    <ns1:level name="users">
                    </ns1:level>
                    <ns1:level name="userid">
                    </ns1:level>
                </ns1:refPath>
            </ns1:match>
         
            <ns1:match name="" crudType="">
                <ns1:fixedDests>
                    <ns1:fixedDest fixedValue="" fixedValueType="UTF8Type">
                        <ns1:dest attr="" where="">
                        </ns1:dest>
                    </ns1:fixedDest>
                </ns1:fixedDests>
                <ns1:refPath>
                    <ns1:level name="">
                    </ns1:level>
                </ns1:refPath>
            </ns1:match>
        </ns1:matches>
    </ns1:cluster>
     

</ns1:env>

=== cugni/aeneas/aeneas-2/cassandra/translator/src/test/java/es/bsc/aeneas/cassandra/translator/MatchingModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<g:env
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:g='http://aeneas.bsc.es/MatchingModel'
    xmlns:cm='http://aeneas.bsc.es/CassandraModel'
    xsi:schemaLocation='http://aeneas.bsc.es/MatchingModel file:/home/ccugnasc/workspace/aeneas/aeneas-core/model/src/main/resources/MatchingModel.xsd
   http://aeneas.bsc.es/CassandraModel file:/home/ccugnasc/workspace/aeneas/cassandra/translator/src/main/resources/CassandraModel.xsd'>
    <g:cluster xsi:type="cm:CassandraClusterType" name="prova" handlerName="prova" address="localhost:">
        <g:settings>
            
        </g:settings>
        <g:matches>
            <g:match id="" crudType="">
                <g:fixedDests>
                    <g:fixedDest fixedValue="" fixedValueType="UTF8Type">
                        <g:dest attr="" where="" from="false" to="false">
                            <g:transform className="" methodName=""></g:transform>
                            <g:transform className="" methodName=""></g:transform>
                            <g:transform className="" methodName=""></g:transform>
                        </g:dest>
                    </g:fixedDest>
                    <g:fixedDest fixedValue="" fixedValueType="UTF8Type">
                        <g:dest attr="" where="" from="false" to="false">
                        </g:dest>
                    </g:fixedDest>
                    <g:fixedDest fixedValue="" fixedValueType="UTF8Type">
                        <g:dest attr="" where="" from="false" to="false">
                        </g:dest>
                    </g:fixedDest>
                </g:fixedDests>
                <g:refPath>
                    <g:level name="">
                        <g:dest attr="" where="" from="false" to="false">
                        </g:dest>
                        <g:dest attr="" where="" from="false" to="false">
                        </g:dest>
                        <g:dest attr="" where="" from="false" to="false">
                        </g:dest>
                    </g:level>
                    <g:level name="">
                    </g:level>
                    <g:level name="">
                    </g:level>
                </g:refPath>
            </g:match>
            <g:match id="" crudType="">
                <g:fixedDests>
                    <g:fixedDest fixedValue="" fixedValueType="UTF8Type">
                        <g:dest attr="" where="" from="false" to="false">
                        </g:dest>
                    </g:fixedDest>
                </g:fixedDests>
                <g:refPath>
                    <g:level name="">
                    </g:level>
                </g:refPath>
            </g:match>
            <g:match id="" crudType="">
                <g:fixedDests>
                    <g:fixedDest fixedValue="" fixedValueType="UTF8Type">
                        <g:dest attr="" where="" from="false" to="false">
                        </g:dest>
                    </g:fixedDest>
                </g:fixedDests>
                <g:refPath>
                    <g:level name="">
                    </g:level>
                </g:refPath>
            </g:match>
        </g:matches>
    </g:cluster>
    <g:cluster name="" handlerName="" address="">
        <g:settings></g:settings>
        <g:matches>
        </g:matches>
    </g:cluster>
    <g:cluster name="" handlerName="" address="">
        <g:settings></g:settings>
        <g:matches>
        </g:matches>
    </g:cluster>

</g:env>
