=== cugni/aeneas/aeneas-1/bscproj1/bsc01-loader-impl/conf/QueryImplementation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://cassamdrabm.bsc.es/QueryImplementation"
        elementFormDefault="qualified"
        xmlns:tns="http://cassamdrabm.bsc.es/QueryImplementation" 
        xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes">

    <import schemaLocation="CommonTypes.xsd" namespace="http://cassamdrabm.bsc.es/CommonTypes"></import>
    <element name="model">
        <complexType>
            <sequence>
                <element name="query" type="tns:queryImplType"
                         maxOccurs="unbounded" minOccurs="1">
                    <key name="varNames">
                        <selector xpath="model/query/var"/>
                        <field xpath="@name"/>
                                 
                    </key>
                </element>
            </sequence>
        </complexType>
    </element>


    <complexType name="queryImplType">
       
		<!-- Set key reference beetween vars name and setResults values-->
        <sequence>
            
            <element name="var" type="tns:varType" maxOccurs="unbounded"
                     minOccurs="0">
            </element>
            <choice>
                <element name="notImplemented"/>
           		<!--Declaration of all the variable (Input, output and temporary) used-->
                
                <element name="getRow" type="tns:getRowType"
                         maxOccurs="unbounded" minOccurs="1">
                </element>
           
            </choice>
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="tempDataType">
        <attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="getRowType">
        <sequence>
            <choice>
                <element name="key" type="tns:composekeyType"></element>
                <element name="rangeKey" type="tns:rangeKeyType"
                         minOccurs="1" maxOccurs="1">
                </element>
            </choice>
            <element name="foreachColumn" type="tns:foreachColumnType"
                     maxOccurs="unbounded" minOccurs="0">
            </element>

        </sequence>
        <attribute name="columnFamily" type="string" use="required"></attribute>
        <attribute name="fetchAllrow" type="boolean" use="optional"/>
    </complexType>
    <complexType name="composekeyType">
        <choice>
            <element name="simple" type="tns:qkeyType"></element>
            <element name="composed" type="tns:qkeyType"
                     maxOccurs="unbounded" minOccurs="1">
            </element>
          
        </choice>
    </complexType>
    <complexType name="qkeyType">
        <choice>
            <element name="varRef" type="string"></element>
            <element name="fixed" type="cmt:fixedType"/>
        </choice>
    </complexType>
    

    <complexType name="varType">
        <complexContent>
            <extension base="cmt:namedType">
                <attribute name="scope" use="required" type="tns:scopeType">
                   
                </attribute>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="scopeType">
        <restriction base="string">
            <enumeration value="INPUT_VAR" />
            <enumeration value="OUTPUT_VAR" />
            <enumeration value="TMP_VAR" />
        </restriction>
    </simpleType>
    <complexType name="foreachColumnType">
        <sequence>
            <choice>
                <element name="columnName" type="tns:composekeyType"></element>
                <element name="columnNameRange"
                         type="tns:rangeKeyType">
                </element>
                <element name="selectAll" type="cmt:Type"/>
                
            </choice>
            
            <element minOccurs="0" name="setResultKey" type="string"></element>
            <element minOccurs="0" name="setResultColumnName"
                     type="string">
            </element>
            <element minOccurs="0" name="setResultColumnValue"
                     type="string">
            </element>
            
        </sequence>
    </complexType>
    
    <complexType name="rangeKeyType">
        <sequence>
            <element name="from" type="tns:composekeyType"></element>
            <element name="to" type="tns:composekeyType"></element>
        </sequence>
        <attribute name="discretize" type="boolean" default="false" />
    </complexType>
</schema>

=== cugni/aeneas/aeneas-core/loader/src/test/resources/columnCompositePxF.qi.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:model
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://cassamdrabm.bsc.es/QueryImplementation'
    xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
    xsi:schemaLocation='http://cassamdrabm.bsc.es/QueryImplementation ../src/main/resources/QueryImplementation.xsd'>
    <ns1:query name="getMetadata">
        <ns1:var name="natoms" scope="OUTPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="prec" scope="OUTPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:getRow columnFamily="frame">
            <ns1:key>
                <ns1:simple>
                    <ns1:fixed type="Int32Type">-1</ns1:fixed>                    
                </ns1:simple>
            </ns1:key>
            <ns1:foreachColumn>
                <ns1:columnName>
                    <ns1:simple>
                        <ns1:fixed type="UTF8Type">natoms</ns1:fixed>  
                    </ns1:simple>
                </ns1:columnName>
                <ns1:setResultColumnValue>natoms</ns1:setResultColumnValue>               
            </ns1:foreachColumn>
            <ns1:foreachColumn>
                <ns1:columnName>
                    <ns1:simple>
                        <ns1:fixed type="UTF8Type">prec</ns1:fixed>       
                    </ns1:simple>
                </ns1:columnName>
                <ns1:setResultColumnValue>prec</ns1:setResultColumnValue>               
            </ns1:foreachColumn>
        </ns1:getRow>
    </ns1:query>
   
    <ns1:query name="getFrameInfo" >
        <ns1:var name="frame" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="step" scope="OUTPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="box" scope="OUTPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:customType>es.bsc.aeneas.model.marshalling.BoxType</cmt:customType>
        </ns1:var>
        <ns1:getRow columnFamily="frame">
            <ns1:key>
                <ns1:simple>
                    <ns1:varRef>frame</ns1:varRef>
                </ns1:simple>
            </ns1:key>
            <ns1:foreachColumn>
                <ns1:columnName>
                    <ns1:simple>
                        <ns1:fixed type="UTF8Type">step</ns1:fixed>     
                    </ns1:simple>
                </ns1:columnName>
                <ns1:setResultColumnValue>step</ns1:setResultColumnValue>
	   
            </ns1:foreachColumn>	
            <ns1:foreachColumn>
                <ns1:columnName>
                    <ns1:simple>
                        <ns1:fixed type="UTF8Type">box</ns1:fixed>       
                    </ns1:simple>
                </ns1:columnName>
                <ns1:setResultColumnValue>box</ns1:setResultColumnValue>
	   
            </ns1:foreachColumn>	 
        </ns1:getRow>
    </ns1:query>
    <ns1:query name="getFramePoints">
        <ns1:var name="frame" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
       
        <ns1:var name="pointFrom" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="pointTo" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="points" scope="OUTPUT_VAR" collectionType="LIST_TYPE">
            <cmt:customType>es.bsc.aeneas.model.marshalling.PointType</cmt:customType>
        </ns1:var>
        <ns1:getRow columnFamily="points">
            <ns1:rangeKey>
                <ns1:from>
                    <ns1:composed>
                        <ns1:varRef>frame</ns1:varRef>
                    </ns1:composed>
                    <ns1:composed>
                        <ns1:varRef>pointFrom</ns1:varRef>
                    </ns1:composed>
                </ns1:from>
                <ns1:to>
                    <ns1:composed>
                        <ns1:varRef>frame</ns1:varRef>
                    </ns1:composed>
                    <ns1:composed>
                        <ns1:varRef>pointTo</ns1:varRef>
                    </ns1:composed>                    
                </ns1:to>
            </ns1:rangeKey>
            <ns1:foreachColumn>
                <ns1:selectAll>
                    <cmt:customType>es.bsc.aeneas.model.marshalling.PointType</cmt:customType>
                </ns1:selectAll>
                <ns1:setResultColumnName>points</ns1:setResultColumnName>
            </ns1:foreachColumn>  
        </ns1:getRow>
    </ns1:query>
    <ns1:query name="getFrameRangePoints">
        <ns1:var name="frameFrom" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="frameTo" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="pointFrom" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="pointTo" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="points" scope="OUTPUT_VAR" collectionType="TABLE_TYPE">
            <cmt:customType>es.bsc.aeneas.model.marshalling.PointType</cmt:customType>
        </ns1:var>
        <ns1:getRow columnFamily="points">
            <ns1:rangeKey>
                <ns1:from>
                    <ns1:composed>
                        <ns1:varRef>frameFrom</ns1:varRef>
                    </ns1:composed>
                    <ns1:composed>
                        <ns1:varRef>pointFrom</ns1:varRef>
                    </ns1:composed>
                </ns1:from>
                <ns1:to>
                    <ns1:composed>
                        <ns1:varRef>frameFrom</ns1:varRef>
                    </ns1:composed>
                    <ns1:composed>
                        <ns1:varRef>pointTo</ns1:varRef>
                    </ns1:composed>                    
                </ns1:to>
            </ns1:rangeKey>
            <ns1:foreachColumn>
                <ns1:selectAll>
                    <cmt:customType>es.bsc.aeneas.model.marshalling.PointType</cmt:customType>
                </ns1:selectAll>
                <ns1:setResultColumnName>points</ns1:setResultColumnName>
            </ns1:foreachColumn>  
        </ns1:getRow>
    </ns1:query>
    
    
    <ns1:query name="getFramePointsByTime">
        <ns1:var name="timeFrom" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>LongType</cmt:standardType>
        </ns1:var>
        <ns1:var name="timeTo" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>LongType</cmt:standardType>
        </ns1:var>
        <ns1:var name="pointFrom" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>
        <ns1:var name="pointTo" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>        
        <ns1:var name="frames" scope="TMP_VAR" collectionType="LIST_TYPE">
            <cmt:standardType>Int32Type</cmt:standardType>
        </ns1:var>	    
        <ns1:var name="points" scope="OUTPUT_VAR" collectionType="TABLE_TYPE">
            <cmt:customType>es.bsc.aeneas.model.marshalling.PointType</cmt:customType>
        </ns1:var>
        <ns1:getRow columnFamily="time">
            <ns1:rangeKey>
                <ns1:from>
                    <ns1:simple>
                        <ns1:varRef>timeFrom</ns1:varRef>
                    </ns1:simple>              
                </ns1:from>
                <ns1:to>
                    <ns1:simple>
                        <ns1:varRef>timeTo</ns1:varRef>
                    </ns1:simple>
                </ns1:to>
            </ns1:rangeKey>   
            <ns1:foreachColumn>
                <ns1:selectAll>
                    <cmt:standardType>Int32Type</cmt:standardType>
                </ns1:selectAll>
                <ns1:setResultColumnName>frames</ns1:setResultColumnName>	
            </ns1:foreachColumn>
        </ns1:getRow>	
        <ns1:getRow columnFamily="points">
            <ns1:rangeKey discretize="true">
                <ns1:from>
                    <ns1:composed>
                        <ns1:varRef>frames</ns1:varRef><!--How to handle it?-->
                    </ns1:composed>
                    <ns1:composed>
                        <ns1:varRef>pointFrom</ns1:varRef>
                    </ns1:composed>
                </ns1:from>
                <ns1:to>
                    <ns1:composed>
                        <ns1:varRef>frames</ns1:varRef>
                    </ns1:composed>
                    <ns1:composed>
                        <ns1:varRef>pointTo</ns1:varRef>
                    </ns1:composed>                    
                </ns1:to>
            </ns1:rangeKey>
            <ns1:foreachColumn>
                 <ns1:selectAll>
                    <cmt:customType>es.bsc.aeneas.model.marshalling.PointType</cmt:customType>
                    </ns1:selectAll>
                <ns1:setResultColumnName>points</ns1:setResultColumnName>
            </ns1:foreachColumn>  
        </ns1:getRow>
      
    </ns1:query>  
    <ns1:query name="getAtoms">
        <ns1:var name="x" scope="INPUT_VAR" collectionType="SIMPLE_TYPE">
            <cmt:standardType>LongType</cmt:standardType>
        </ns1:var>
