=== cugni/aeneas/aeneas-1/bscproj1/bsc01-loader-impl/conf/ReferenceModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://cassamdrabm.bsc.es/ReferenceModel" 
        xmlns:tns="http://cassamdrabm.bsc.es/ReferenceModel"
        xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
        elementFormDefault="qualified">
    <import schemaLocation="CommonTypes.xsd" namespace="http://cassamdrabm.bsc.es/CommonTypes"></import>
  
    <complexType name="entityType">
        <sequence>
            <choice>
                <element name="keyType" type="cmt:standardType"></element>
                <element name="keyValue" type="string"></element>            
            </choice>
            <element name="value" type="tns:valueType"></element>
        </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>
    <complexType name="rootType">
        <sequence>
            <element name="entity" type="tns:entityType" maxOccurs="unbounded"></element>
        </sequence>
    </complexType>


    <complexType name="valueType">

        <choice>
            <element name="simpleValue" type="cmt:Type" />
            <element name="nodeValue" type="tns:complexValueType">
                <key name="nameUnique">
                    <selector xpath="./tns:entityType"></selector>
                    <field xpath="@name"></field>
                </key>
            </element>
<!--            <element name="listValue" type="cmt:Type"></element>-->
        </choice>
    </complexType>


    <complexType name="complexValueType">


        <sequence>
            <element name="entity" type="tns:entityType" maxOccurs="unbounded">
    		
            </element>
        </sequence>
    </complexType>
    

    <element name="root" type="tns:rootType" >

   
    </element>
</schema>

=== cugni/aeneas/aeneas-2/cassandra/metrics-recorder/src/main/resources/MetricsReferenceModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://cassamdrabm.bsc.es/ReferenceModel"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
          xsi:schemaLocation="http://cassamdrabm.bsc.es/ReferenceModel    ../../../../model/src/main/resources/ReferenceModel.xsd
http://cassamdrabm.bsc.es/CommonTypes ../../../../model/src/main/resources/CommonTypes.xsd">
    <tns:entity name="context" >
        <tns:keyType>UTF8Type</tns:keyType>
        <tns:value>
            <tns:nodeValue>
                <tns:entity name="testname" >
                    <tns:keyType>UTF8Type</tns:keyType>
                    <tns:value>
                        <tns:nodeValue>
                            <tns:entity name="location" >
                                <tns:keyType>UTF8Type</tns:keyType>
                                <tns:value>
                                    <tns:nodeValue>
                                        <tns:entity name="time" >
                                            <tns:keyType>LongType</tns:keyType>
                                            <tns:value>
                                                <tns:nodeValue>
                                                    <tns:entity name="attribute" >
                                                        <tns:keyType>UTF8Type</tns:keyType>
                                                        <tns:value>
                                                            <tns:simpleValue>
                                                                <cmt:standardType>AnyType</cmt:standardType>
                                                            </tns:simpleValue>  
                                                        </tns:value>
                                                    </tns:entity>
                                                </tns:nodeValue>
                                            </tns:value>
                                        </tns:entity>
                                   
                                        <tns:entity name="start" >
                                            <tns:keyValue>start</tns:keyValue>
                                            <tns:value>
                                                <tns:simpleValue>
                                                    <cmt:standardType>LongType</cmt:standardType>
                                                </tns:simpleValue>
                                            </tns:value>
                                        </tns:entity>                                   
                                        <tns:entity name="stop" >
                                            <tns:keyValue>stop</tns:keyValue>
                                            <tns:value>
                                                <tns:simpleValue>
                                                    <cmt:standardType>LongType</cmt:standardType>
                                                </tns:simpleValue>
                                            </tns:value>
                                        </tns:entity>
                                    </tns:nodeValue>
                                </tns:value>
                            </tns:entity>
                        </tns:nodeValue>
                    </tns:value>
                </tns:entity>
            </tns:nodeValue>
        </tns:value>
    </tns:entity>
</tns:root>

=== cugni/aeneas/aeneas-2/aeneas-core/model/src/test/resources/referenceModelTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://aeneas.bsc.es/ReferenceModel"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:cmt="http://aeneas.bsc.es/CommonTypes"
          xsi:schemaLocation="http://aeneas.bsc.es/ReferenceModel ../../main/resources/ReferenceModel.xsd">
    <tns:entity name="frame" >
        <tns:keyType>Int32Type</tns:keyType>
        <tns:value>
            <tns:nodeValue>
                <tns:entity name="natoms" >
                    <tns:keyValue>natoms</tns:keyValue>
                    <tns:value>
                        <tns:simpleValue>
                            <cmt:standardType>AnyType</cmt:standardType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>
                <tns:entity name="step" >
                    <tns:keyValue>step</tns:keyValue>
                    <tns:value>
                        <tns:simpleValue> 
                            <cmt:standardType>Int32Type</cmt:standardType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>
                <tns:entity name="time" >
                    <tns:keyValue>time</tns:keyValue>
                    <tns:value>
                        <tns:simpleValue> 
                            <cmt:standardType>LongType</cmt:standardType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>
                <tns:entity name="prec" >
                    <tns:keyValue>prec</tns:keyValue>
                    <tns:value>
                        <tns:simpleValue> 
                            <cmt:standardType>Int32Type</cmt:standardType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>
                <tns:entity name="box" >
                    <tns:keyValue>box</tns:keyValue>
                    <tns:value>
                        <tns:simpleValue>
	<cmt:customType>es.bsc.aeneas.model.marshalling.BoxType</cmt:customType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>	
                <tns:entity name="points" >
                    <tns:keyValue>points</tns:keyValue>
                    <tns:value>
                        <tns:nodeValue>
                            <tns:entity name="index">
                                <tns:keyType>Int32Type</tns:keyType>
                                <tns:value>
                                    <tns:simpleValue>
                                        <cmt:customType>es.bsc.aeneas.model.marshalling.PointType</cmt:customType>
                                        </tns:simpleValue>
                                </tns:value>
                            </tns:entity>
                        </tns:nodeValue>
                    </tns:value>
                </tns:entity>
            </tns:nodeValue>
        </tns:value>
    </tns:entity>
</tns:root>

=== cugni/aeneas/aeneas-1/CassandraBM/model/src/main/resources/NodeAgentReferenceModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://cassamdrabm.bsc.es/ReferenceModel"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
          xsi:schemaLocation="http://cassamdrabm.bsc.es/ReferenceModel  ReferenceModel.xsd">
    <tns:entity name="context" >
        <tns:keyType>UTF8Type</tns:keyType>
        <tns:value>
            <tns:nodeValue>
                <tns:entity name="testname" >
                    <tns:keyType>UTF8Type</tns:keyType>
                    <tns:value>
                        <tns:nodeValue>
                            <tns:entity name="location" >
                                <tns:keyType>UTF8Type</tns:keyType>
                                <tns:value>
                                    <tns:nodeValue>
                                        <tns:entity name="time" >
                                            <tns:keyType>LongType</tns:keyType>
                                            <tns:value>
                                                <tns:nodeValue>
                                                         <tns:entity name="attribute" >
                                                        <tns:keyType>UTF8Type</tns:keyType>
                                                        <tns:value>
                                                            <tns:simpleValue>
                                                                <cmt:standardType>Int32Type</cmt:standardType>
                                                            </tns:simpleValue>  
                                                            <tns:simpleValue>
                                                                <cmt:standardType>DoubleType</cmt:standardType>
                                                            </tns:simpleValue>
                                                            <tns:simpleValue>
                                                                <cmt:standardType>UTF8Type</cmt:standardType>
                                                            </tns:simpleValue>
                                                        </tns:value>
                                                    </tns:entity>
                                                </tns:nodeValue>
                                            </tns:value>
                                        </tns:entity>
                                    </tns:nodeValue>
                                    <tns:nodeValue>
                                        <tns:entity name="start" >
                                            <tns:keyValue>start</tns:keyValue>
                                            <tns:value>
                                                <tns:simpleValue>
                                                    <cmt:standardType>LongType</cmt:standardType>
                                                </tns:simpleValue>
                                            </tns:value>
                                        </tns:entity>
                                    </tns:nodeValue>
                                    <tns:nodeValue>
                                        <tns:entity name="stop" >
                                            <tns:keyValue>start</tns:keyValue>
                                            <tns:value>
                                                <tns:simpleValue>
                                                    <cmt:standardType>LongType</cmt:standardType>
                                                </tns:simpleValue>
                                            </tns:value>
                                        </tns:entity>
                                    </tns:nodeValue>
                                </tns:value>
                            </tns:entity>
                        </tns:nodeValue>
                    </tns:value>
                </tns:entity>
            </tns:nodeValue>
        </tns:value>
    </tns:entity>
</tns:root>

=== cugni/aeneas/aeneas-1/CassandraBM/node-agent/src/main/resources/WorkspaceReferenceModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://cassamdrabm.bsc.es/ReferenceModel"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:cmt="http://cassamdrabm.bsc.es/CommonTypes"
          xsi:schemaLocation="http://cassamdrabm.bsc.es/ReferenceModel    ../../../../model/src/main/resources/ReferenceModel.xsd
http://cassamdrabm.bsc.es/CommonTypes ../../../../model/src/main/resources/CommonTypes.xsd">
    <tns:entity name="workspace" >
        <tns:keyType>UTF8Type</tns:keyType>
        <tns:value>
            <tns:nodeValue>
                <tns:entity name="desc" >
                    <tns:keyType>UTF8Type</tns:keyType>
                    <tns:value>
                        <tns:simpleValue>
                            <cmt:standardType>UTF8Type</cmt:standardType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>
                <tns:entity name="creationTime" >
                    <tns:keyType>UTF8Type</tns:keyType>
                    <tns:value>
                        <tns:simpleValue>
                            <cmt:standardType>LongType</cmt:standardType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>
                <tns:entity name="modificationTime" >
                    <tns:keyType>UTF8Type</tns:keyType>
                    <tns:value>
                        <tns:simpleValue>
                            <cmt:standardType>LongType</cmt:standardType>
                        </tns:simpleValue>
                    </tns:value>
                </tns:entity>
                
                <tns:entity name="sets" >
                    <tns:keyValue>sets</tns:keyValue>                    
                    <tns:value>
                        <tns:nodeValue>
                            <tns:entity name="sname" >
                                <tns:keyType>UTF8Type</tns:keyType>  
                                <tns:value>
                                    <tns:simpleValue>
                                        <!--JSON encoded data -->
                                        <cmt:standardType>UTF8Type</cmt:standardType>
                                    </tns:simpleValue>
                                </tns:value>
                            </tns:entity>
                    
                        </tns:nodeValue>
                    </tns:value>
                </tns:entity>
                
                <tns:entity name="snippets" >
                    <tns:keyValue>snippets</tns:keyValue>                    
                    <tns:value>
                        <tns:nodeValue>
                            <tns:entity name="sname" >
                                <tns:keyType>UTF8Type</tns:keyType>  
                                <tns:value>
                                    <tns:nodeValue>
                                        <tns:entity name="tag">
                                            <tns:keyValue>tag</tns:keyValue>
                                            <tns:value>
                                                <tns:simpleValue>
                                                    <cmt:standardType>UTF8Type</cmt:standardType>
                                                </tns:simpleValue>
                                            </tns:value>
                                        </tns:entity>
                                        <tns:entity name="data">
                                            <tns:keyValue>data</tns:keyValue>
                                            <tns:value>
                                                <tns:nodeValue>
                                                    <tns:entity name="time">
                                                        <tns:keyType>LongType</tns:keyType>
                                                        <tns:simpleValue>
                                                            <!--JSON encoded data -->
                                                            <cmt:standardType>UTF8Type</cmt:standardType>
                                                        </tns:simpleValue>
                                                    </tns:entity>
                                            </tns:value>
                                        </tns:entity>
                                    </tns:nodeValue>                             
                                </tns:value>
                            </tns:entity>
                        </tns:nodeValue>                
                    </tns:value>
                </tns:entity> 
            </tns:nodeValue>
        </tns:value>
    </tns:entity>
</tns:root>

=== cugni/aeneas/cassandra/translator/src/test/java/es/bsc/aeneas/cassandra/translator/refmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://aeneas.bsc.es/ReferenceModel'
    xsi:schemaLocation='http://aeneas.bsc.es/ReferenceModel file:/home/ccugnasc/workspace/aeneas/aeneas-core/model/src/main/resources/ReferenceModel.xsd'>
    <entity name="">
        <keyType></keyType>
        <value>
            <simpleValue collectionType="SIMPLE_TYPE">
                <ns2:standardType></ns2:standardType>
            </simpleValue>
        </value>
    </entity>
    <entity name="">
        <keyType></keyType>
        <value>
          
            <simpleValue collectionType="MAP_TYPE">
                <ns2:standardType></ns2:standardType>
            </simpleValue>
        </value>
    </entity>
    <entity name="">
        <keyType></keyType>
        <value>
            <simpleValue collectionType="SIMPLE_TYPE">
                <ns2:standardType></ns2:standardType>
            </simpleValue>
        </value>
    </entity>

</root>
